### PR TITLE
Fix Qwt plot engine

### PR DESCRIPTION
**Pull request by rhaschke**
The Qwt plot engine is broken, probably since years. There are two Python Qwt packages available in Ubuntu Bionic and Focal and both of them are incompatible to the code in qwt_data_plot.py:
- [`python3-pyqt5.qwt`](https://packages.ubuntu.com/focal/python3-pyqt5.qwt)
  This seems to be a 1:1 wrapper of the C++ lib. It doesn't support `setData()` from numpy arrays as required by rqt_plot.
- [`python[3]-qwt`](https://packages.ubuntu.com/focal/python3-qwt) build from https://github.com/PierreRaybaut/PythonQwt
  This attempts to be a pythonic replacement of the old, now unavailable `PyQwt` package. It is mostly compatible to the existing code. But, the package name changed from `Qwt` to `qwt` and it doesn't provide a picker anymore:
  > The following Qwt classes won't be reimplemented in qwt because more powerful features already exist in guiqwt: QwtPlotZoomer, QwtCounter, QwtEventPattern, QwtPicker, QwtPlotPicker.

This PR comprises a minimal set of changes to get Qwt working again.
I also added a grid (like in matplotlib).
I further suggest to rename `Qwt` to `qwt` througout the rqt_plot's code to match the new package name, but I would like to get feedback from a maintainer first.
I didn't yet manage to get the simple distance measuring working again (and don't have time to put more effort into this).

### CODE REVIEW

**Comment by mabelzhang** [comment]
Sorry for the delay. I had to do some homework to understand what this is about.

What I understand is, as of Kinetic, which uses Qt5, there has been no Python package for Qwt6, as stated in #12. Hence qwt has been broken since then.
For Indigo and prior, Python for Qwt5 and Qt4 existed and was used as a dependency.
This repo's dependency on `qwt_dependency` makes that distinction. For Indigo, `qwt_dependency` depended on `python-qt-bindings-qwt5`, and for Kinetic and above, that dependency has been commented out, so the dependency does nothing.

This PR intends to fix that missing dependency of Python for Qwt6 and Qt5.
Since the `master` branch of this repo goes to Kinetic, Melodic, and Noetic, ideally, the new system dependency should exist on xenial, bionic, and focal (or we can break up multiple branches).

The first one suggested in the original description, `python3-pyqt5.qwt`, only exists on Focal. So that rules it out for Kinetic and Melodic, other than that it isn't compatible with `setData()` (I haven't looked into that part).

The second one sounds like the better choice, `python[3]-qwt` does exist on xenial, bionic, and focal, but when I installed `python3-qwt` on bionic, it gave me a lot of Qt4 packages, notably `python3-pyqt4`, which leads to this error:
```
$ python3 qwt_data_plot.py
RuntimeError: the PyQt4.QtCore and PyQt5.QtCore modules both wrap the QObject class
```
because Melodic on bionic uses Qt5, so now I end up having both Qt4 and Qt5, and they're clashing.

So the first question is, is that supposed to happen, that `python3-qwt` is for Qt4 (the Ubuntu package page doesn't say what Qt version it's for)? Which ROS distro + Ubuntu did you test on?

I haven't tested on Kinetic and Noetic yet. This seems a bit involved. Whichever package we end up choosing, if we do, maybe we want to update `qwt_dependency` or retire it, and maybe we need to add a rosdep key. All that is to say I might need to pull in some help from other maintainers.

I do recall you wanted a release of the repo for the earlier fix. Let me know if a release before we sort out this PR would help. I can do that before we figure out what to do with this one.

**Comment by rhaschke** [comment]
> This PR intends to fix that missing dependency of Python for Qwt6 and Qt5.

Kind of. Actually, I wasn't aware of [the disabled dependency](https://github.com/ros-visualization/qwt_dependency/blob/91d8aeefb791b3e1c30a94e3babfc12fca5d0a70/package.xml#L13-L14). So, this PR only adapts the source code to work with `python3-qwt`.

> So the first question is, is that supposed to happen, that `python3-qwt` is for Qt4? Which ROS distro + Ubuntu did you test on?

Indeed, I only tested this on Focal and ROS Noetic. Older versions still seem to depend on Qt4. I think we can only target this PR at Noetic. Reactivating the dependency in `qwt_dependency` is a good idea. So far, I considered the Qwt plotting approach as optional.

> I do recall you wanted a release of the repo for the earlier fix. Let me know if a release before we sort out this PR would help. I can do that before we figure out what to do with this one.

If merging this PR will take more time, I will appreciate an earlier release. Thanks.

**Comment by mabelzhang** [comment]
Okay, I've gone ahead and made a release for now.

For this PR, I'll need to test on Noetic and report back. Probably we'll want to make a new branch in `qwt_dependency` for `noetic-devel` and release that, and then this fix will just be for Noetic, so Qwt plot will remain in its non-working state for Kinetic and Melodic.

**Review by mabelzhang — COMMENTED** [review]
So, I tested this in Noetic. I don't have another script that readily instantiates `QwtDataPlot`, so I just ran the script directly with `python3 qwt_data_plot.py`. Comically, that revealed that `main()` has been broken with its calls to a non-existent `update_value`, passing in the wrong number of parameters ever since the file's creation, with a mismatch between the y data and the caption, and the function has been changed to `set_values` years ago, which doesn't process the `curve_id` properly.

While we're here, with your permission, I can push the fix to your branch so that they're included in this PR.

With those fixes, the default plot looks like this:
Screenshot from 2021-03-05 03-17-43

I think that tests the grid part added in `__init__`? I wasn't able to get the mouse event to do anything though. It just shows the default help tool tip for me. Do I need to click on the curve itself, or can I click anywhere in the plot area? Does a trackpad work? I didn't get anything to happen with either a mouse or a trackpad.

**Comment by rhaschke** [comment]
> While we're here, with your permission, I can push the fix to your branch so that they're included in this PR.

Sure. Please, push your commit onto my PR branch. I didn't touch `main()`.

> I wasn't able to get the mouse event to do anything though.

Left-mouse button measuring doesn't work anymore, but middle-button moving and right-button scaling does for me.

**Comment by rhaschke** [comment]
Do you think, this is ready for merging?

**Comment by mabelzhang** [comment]
It looks like the latest commit undid some of the fixes for main()? Not sure if there was a merge problem. The 5 in the first plot should be 500, and the QApplication import line won't work, the numpy import at the top can also be removed. The `set_values` treatment of the `curve_id` should be consistent with `add_curve` and `remove_curve`, both convert it to string first.

**Comment by rhaschke** [comment]
I went for a minimal set of changes to main(). The code works for me as is. Did you observe any issues?

**Comment by rhaschke** [comment]
@mabelzhang, I just noticed that this is still pending. Did you observe any issues testing this PR?

**Comment by mabelzhang** [comment]
Hey sorry, I haven't had any time to spend on ROS. I guess the state of it is fine. In the above, I tried to fix what's actually a bug in the current code. If you want to stick with a minimal set of changes - which means the bug is still there, that's fine because it fixes another problem. I can approve and merge as it is.

**Comment by rhaschke** [comment]
Obviously, I had issues understanding your feedback in https://github.com/ros-visualization/rqt_plot/pull/70#issuecomment-793185286. Looking more precisely, I think I got your points:
- The 5 in the first plot should be 500
  I adapted the 500 to 5 to have a similar scale as for the `sin` function. I changed _both_ to 50 now.
- The `QApplication` import line won't work
  I cannot see any issue with this line. It works like a charm for me.
- The numpy import at the top can also be removed.
  You are right. Done.
- The `set_values` treatment of the `curve_id` should be consistent with `add_curve` and `remove_curve`, both convert it to string first.
  Well spotted. Fixed now as well.

I hope this is ready for merging now. Please feel free to squash-merge. I just pushed single commits to cleanly state what has changed.

**Comment by rhaschke** [comment]
Hi @mabelzhang, may I ping you again on this, before we both forget about the details of this PR again?

**Comment by mabelzhang** [comment]
Thanks for iterating! I tested the latest version on Noetic. It works.

A few things need to be done before this PR can be merged:
1. Since this introduces a new dependency of `python3-qwt`, a rosdep key needs to be created for it on https://github.com/ros/rosdistro
   I opened a PR https://github.com/ros/rosdistro/pull/31201
2. https://github.com/ros-visualization/qwt_dependency needs a new `noetic-devel` branch. The new rosdep key needs to be added to  `package.xml`
  Update: PR opened https://github.com/ros-visualization/qwt_dependency/pull/3
  Update: Released https://github.com/ros/rosdistro/pull/31349
3. Since this PR only works in Noetic (as discussed above, because of older qt version on Bionic for Melodic), a `noetic-devel` branch needs to be created in this repo, and this PR needs to be retargeted to `noetic-devel`.
   (OR merge into `master` since it doesn't work for Kinetic and Melodic anyway...)

While that rosdistro PR is being reviewed, I'm checking with people that these are the right steps.

**Comment by rhaschke** [comment]
Should we really continue using the `qwt_dependency` package as a proxy for the required qwt dependencies?
Why not simply declare the (single) required dependency here? With [`package.xml, format 3`](https://www.ros.org/reps/rep-0149.html) we could even specify different versions for python2 and python3, but that's not even needed as we can target Noetic only, not Melodic.
The only two packages using `qwt_dependency` are:
```sh
$ rospack depends-on qwt_dependency
rqt_bag_plugins
rqt_plot
```

**Comment by mabelzhang** [comment]
Yeah, `qwt_dependency` is the preferred way, to be consistent with how the other distros have been using it. That package is an empty package specifically created to make the distinction of qwt dependencies on different distros (see https://github.com/ros-visualization/qwt_dependency/pull/2#pullrequestreview-510609148). Bypassing it would defeat the purpose of having created it.

**Comment by mabelzhang** [comment]
The rosdep key `python3-qwt` has been created on rosdistro, and `qwt_dependency` in Noetic now depends on it.
I've udpated the comment above https://github.com/ros-visualization/rqt_plot/pull/70#issuecomment-966960243 with the links to the PRs.

I've created a `noetic-devel` branch in this repo (we decided this is the more proper way).

Could you retarget this PR to `noetic-devel`?

**Comment by rhaschke** [comment]
> Could you retarget this PR to `noetic-devel`?

Sure. Done.

**Review by mabelzhang — APPROVED** [review]
Thank you for iterating! Will merge and release the new branch into Noetic. Hope the new rosdep key works.

**Comment by mabelzhang** [comment]
Released https://github.com/ros/rosdistro/pull/31369

**Comment by rhaschke** [comment]
Thanks a lot, @mabelzhang.

**Pull request merged**
